CC = arm-none-eabi-gcc

#Drapeaux de l'exercice
CFLAGS = -Wall -Werror -g -O1 -mthumb
LDLIBS = -lm
LDFLAGS = -mthumb

SOURCES = exo2.c
OBJS = exo2.o
EXE = exo2

exo2: exo2.o

clean:
	rm -f $(OBJS) $(EXE)
