#include <stdint.h>
#include "stm32l4xx.h"
#include "matrix.h"
#include "main.h"

void matrix_init(){
	//Activation des horloges des ports A, B et C
	SET_BIT(RCC->AHB2ENR, RCC_AHB2ENR_GPIOAEN | RCC_AHB2ENR_GPIOBEN | RCC_AHB2ENR_GPIOCEN);
	//Activation des différentes broches PC3,4,5 PB0,1,2 PA2,3,4,5,6,7,15
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE2_1 | GPIO_MODER_MODE3_1 | GPIO_MODER_MODE4_1 | GPIO_MODER_MODE5_1 | GPIO_MODER_MODE6_1 | GPIO_MODER_MODE7_1 | GPIO_MODER_MODE15_1 , GPIO_MODER_MODE2_0 | GPIO_MODER_MODE3_0 | GPIO_MODER_MODE4_0 | GPIO_MODER_MODER5_0 | GPIO_MODER_MODER6_0 | GPIO_MODER_MODER7_0 | GPIO_MODER_MODER15_0);
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE0_1 | GPIO_MODER_MODE1_1 | GPIO_MODER_MODE2_1, GPIO_MODER_MODE0_0 | GPIO_MODER_MODE1_0 | GPIO_MODER_MODE2_0);
	MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODE3_1 | GPIO_MODER_MODE4_1 | GPIO_MODER_MODE5_1, GPIO_MODER_MODE3_0 | GPIO_MODER_MODE4_0 | GPIO_MODER_MODE5_0);
	//Mise aux bons états des différentes broches
	SET_BIT(GPIOC->BSRR, GPIO_BSRR_BR3 | GPIO_BSRR_BS4 | GPIO_BSRR_BS5);
	SET_BIT(GPIOA->BSRR, GPIO_BSRR_BR4 | GPIO_BSRR_BR15 |GPIO_BSRR_BR2 |GPIO_BSRR_BR7 |GPIO_BSRR_BR6 |GPIO_BSRR_BR5 |GPIO_BSRR_BR3);
	SET_BIT(GPIOB->BSRR, GPIO_BSRR_BR1 | GPIO_BSRR_BR2 | GPIO_BSRR_BR0);
	wait(10000);
	SET_BIT(GPIOC->BSRR, GPIO_BSRR_BS3);	

}

void pulse_SCK(){
	SCK(0);
	wait(3);
	SCK(1);
	wait(3);
	SCK(0);
	wait(3);
}

void pulse_LAT(){
	LAT(1);
	wait(3);
	LAT(0);
	wait(1);
	LAT(1);
	wait(3);
}

void deactivate_rows(){

}

void activate_rows(){

}	
