#include "stm32l4xx.h"
#include "uart.h"

void uart_init(){
	//Activation horloge port B
	SET_BIT(RCC->AHB2ENR, RCC_AHB2ENR_GPIOBEN);
	//Passage en mode Alternate function PB7 10 RX
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE7_0, GPIO_MODER_MODE7_1);
	//Passage en mode Alternate function PB6 10 TX
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE6_0, GPIO_MODER_MODE6_1);	
	//Activation registre AFRL mode AF7 pour PB6 et PB7	
	MODIFY_REG(GPIOB->AFRL, GPIO_AFRL_AFSEL6_3, (GPIO_AFRL_AFSEL6_0 | GPIO_AFRL_AFSEL6_1 | GPIO_AFRL_AFSEL6_2));	
	MODIFY_REG(GPIOB->AFRL, GPIO_AFRL_AFSEL7_3, (GPIO_AFRL_AFSEL7_0 | GPIO_AFRL_AFSEL7_1 | GPIO_AFRL_AFSEL7_2));	
	//Activation de l'horloge de USART1
	SET_BIT(RCC->APB2ENR, RCC_APB2ENR_USART1EN);
	//Specifier l'horloge de USART1 en PCLK 00
	CLEAR_BIT(RCC->CCIPR, (RCC_CCIPR_USART1SEL_1 | RCC_CCIPR_USART1SEL_0));	
	//Reset du port APB2
	RCC->APB2RSTR = 0x0;
	//Configuration de la vitesse 80M/115200=694d=0x2B6
	USART1->BRR = 0x2B6;
	//Oversampling à 16
	CLEAR_BIT(USART->CR1, USART_CR1_OVER8);
	//Passage en 8N1
	CLEAR_BIT(USART->CR1, (USART_CR1_M0 | USART_CR1_M1);
	CLEAR_BIT(USART->CR1, USART_CR1_PCE);
	CLEAR_BIT(USART->CR2, (USART_CR2_STOP_0 | USART_CR2_STOP_1) );
	//Activation UE, RE, TE
	SET_BIT(USART->CR1, USART_CR1_UE);
	SET_BIT(USART->CR1, USART_CR1_RE);
	SET_BIT(USART->CR1, USART_CR1_TE);	
}
